blog_blog_homepage:
    path:     /
    defaults: { _controller: BlogBlogBundle:Default:index }
blog_blog_register:
    path:     /register
    defaults: { _controller: BlogBlogBundle:Default:register }
blog_blog_login:
    path:     /login
    defaults: { _controller: BlogBlogBundle:Default:login }
blog_blog_logout:
    path:     /logout
    defaults: { _controller: BlogBlogBundle:Default:logout }
blog_blog_info:
    path:     /info
    defaults: { _controller: BlogBlogBundle:Default:info }
blog_blog_admin:
    path:     /admin
    defaults: { _controller: BlogBlogBundle:Default:admin }
blog_blog_addPost:
    path:     /addPost
    defaults: { _controller: BlogBlogBundle:Default:addPost }
blog_blog_showPost:
    path:     /showPost/{id}
    defaults: { _controller: BlogBlogBundle:Default:showPost }
    requirements:
        id: \d+
